### ISSUE TITLE
Milestone: Kosu full system beta requirements

### ISSUE THREAD

**Issue by pasiphae00** [ParadigmFoundation/kosu-monorepo#192]
## Overview

This issue will serve as a place to record and track the necessary steps left to prepare the full Kosu system for a public beta. It will outline what that beta should look like, and refer each step to another issue. 

## Description

After all of the following issues are closed, we can consider the Kosu system ready for a public beta. 

- [x] Feature completion of the `go-kosu` MVP (#193 )
- [x] Finalization of the bonding curve parameterization (#155)
- [x] Finalization of the MVP contract system (#194)
- [x] Update and complete the Kosu portal suite (#195)
- [ ] Plan a public, incentivized testnet (#196)

And finally, after all of the above are complete:

- [ ] Announce Kosu: open testnet, make repo public, and new whitepaper (#197)

## Notes

Please use this issue as a place to discuss high-level concerns and considerations of a public beta system, but refer to the sub-issues for specific discussion on each item.
